// Comprehensive genre list for fiction and creative non-fiction.
// Grouped by category for the dropdown UI.

export interface GenreOption {
  value: string;
  label: string;
  category: string;
}

export const GENRE_OPTIONS: GenreOption[] = [
  // ── Core Fiction Genres ──
  { value: "thriller", label: "Thriller", category: "Core Fiction" },
  { value: "romance", label: "Romance", category: "Core Fiction" },
  { value: "fantasy", label: "Fantasy", category: "Core Fiction" },
  { value: "science-fiction", label: "Science Fiction", category: "Core Fiction" },
  { value: "mystery", label: "Mystery", category: "Core Fiction" },
  { value: "horror", label: "Horror", category: "Core Fiction" },
  { value: "historical-fiction", label: "Historical Fiction", category: "Core Fiction" },
  { value: "contemporary", label: "Contemporary", category: "Core Fiction" },
  { value: "literary-fiction", label: "Literary Fiction", category: "Core Fiction" },
  { value: "young-adult", label: "Young Adult", category: "Core Fiction" },
  { value: "new-adult", label: "New Adult", category: "Core Fiction" },
  { value: "middle-grade", label: "Middle Grade", category: "Core Fiction" },
  { value: "childrens", label: "Children's", category: "Core Fiction" },
  { value: "adventure", label: "Adventure", category: "Core Fiction" },
  { value: "action", label: "Action", category: "Core Fiction" },
  { value: "western", label: "Western", category: "Core Fiction" },
  { value: "crime", label: "Crime", category: "Core Fiction" },
  { value: "suspense", label: "Suspense", category: "Core Fiction" },
  { value: "noir", label: "Noir", category: "Core Fiction" },
  { value: "gothic", label: "Gothic", category: "Core Fiction" },
  { value: "magical-realism", label: "Magical Realism", category: "Core Fiction" },
  { value: "speculative-fiction", label: "Speculative Fiction", category: "Core Fiction" },
  { value: "satire", label: "Satire", category: "Core Fiction" },
  { value: "tragedy", label: "Tragedy", category: "Core Fiction" },
  { value: "comedy", label: "Comedy", category: "Core Fiction" },
  { value: "tragicomedy", label: "Tragicomedy", category: "Core Fiction" },
  { value: "absurdist", label: "Absurdist", category: "Core Fiction" },
  { value: "surreal", label: "Surreal", category: "Core Fiction" },
  { value: "fable", label: "Fable", category: "Core Fiction" },
  { value: "fairy-tale", label: "Fairy Tale", category: "Core Fiction" },
  { value: "mythology", label: "Mythology", category: "Core Fiction" },
  { value: "legend", label: "Legend", category: "Core Fiction" },
  { value: "folklore", label: "Folklore", category: "Core Fiction" },
  { value: "epic", label: "Epic", category: "Core Fiction" },
  { value: "saga", label: "Saga", category: "Core Fiction" },
  { value: "bildungsroman", label: "Bildungsroman (Coming of Age)", category: "Core Fiction" },
  { value: "epistolary", label: "Epistolary", category: "Core Fiction" },
  { value: "picaresque", label: "Picaresque", category: "Core Fiction" },
  { value: "metafiction", label: "Metafiction", category: "Core Fiction" },
  { value: "experimental", label: "Experimental", category: "Core Fiction" },

  // ── Fantasy Subgenres ──
  { value: "high-fantasy", label: "High Fantasy", category: "Fantasy" },
  { value: "low-fantasy", label: "Low Fantasy", category: "Fantasy" },
  { value: "urban-fantasy", label: "Urban Fantasy", category: "Fantasy" },
  { value: "dark-fantasy", label: "Dark Fantasy", category: "Fantasy" },
  { value: "grimdark", label: "Grimdark", category: "Fantasy" },
  { value: "sword-and-sorcery", label: "Sword & Sorcery", category: "Fantasy" },
  { value: "portal-fantasy", label: "Portal Fantasy", category: "Fantasy" },
  { value: "epic-fantasy", label: "Epic Fantasy", category: "Fantasy" },
  { value: "cozy-fantasy", label: "Cozy Fantasy", category: "Fantasy" },
  { value: "romantasy", label: "Romantasy", category: "Fantasy" },
  { value: "mythic-fantasy", label: "Mythic Fantasy", category: "Fantasy" },
  { value: "arthurian", label: "Arthurian", category: "Fantasy" },
  { value: "dragon-fantasy", label: "Dragon Fantasy", category: "Fantasy" },
  { value: "fae-fantasy", label: "Fae Fantasy", category: "Fantasy" },
  { value: "wuxia", label: "Wuxia", category: "Fantasy" },
  { value: "xianxia", label: "Xianxia", category: "Fantasy" },
  { value: "litrpg", label: "LitRPG", category: "Fantasy" },
  { value: "progression-fantasy", label: "Progression Fantasy", category: "Fantasy" },
  { value: "gaslamp-fantasy", label: "Gaslamp Fantasy", category: "Fantasy" },
  { value: "flintlock-fantasy", label: "Flintlock Fantasy", category: "Fantasy" },
  { value: "silk-road-fantasy", label: "Silk Road Fantasy", category: "Fantasy" },
  { value: "african-fantasy", label: "African Fantasy", category: "Fantasy" },
  { value: "indian-fantasy", label: "Indian Fantasy", category: "Fantasy" },
  { value: "arabian-fantasy", label: "Arabian Fantasy", category: "Fantasy" },
  { value: "nordic-fantasy", label: "Nordic Fantasy", category: "Fantasy" },
  { value: "celtic-fantasy", label: "Celtic Fantasy", category: "Fantasy" },
  { value: "slavic-fantasy", label: "Slavic Fantasy", category: "Fantasy" },
  { value: "japanese-fantasy", label: "Japanese Fantasy", category: "Fantasy" },

  // ── Sci-Fi Subgenres ──
  { value: "hard-sci-fi", label: "Hard Sci-Fi", category: "Science Fiction" },
  { value: "soft-sci-fi", label: "Soft Sci-Fi", category: "Science Fiction" },
  { value: "cyberpunk", label: "Cyberpunk", category: "Science Fiction" },
  { value: "steampunk", label: "Steampunk", category: "Science Fiction" },
  { value: "biopunk", label: "Biopunk", category: "Science Fiction" },
  { value: "solarpunk", label: "Solarpunk", category: "Science Fiction" },
  { value: "dieselpunk", label: "Dieselpunk", category: "Science Fiction" },
  { value: "atompunk", label: "Atompunk", category: "Science Fiction" },
  { value: "space-opera", label: "Space Opera", category: "Science Fiction" },
  { value: "military-sci-fi", label: "Military Sci-Fi", category: "Science Fiction" },
  { value: "space-western", label: "Space Western", category: "Science Fiction" },
  { value: "alien-invasion", label: "Alien Invasion", category: "Science Fiction" },
  { value: "first-contact", label: "First Contact", category: "Science Fiction" },
  { value: "time-travel", label: "Time Travel", category: "Science Fiction" },
  { value: "alternate-history", label: "Alternate History", category: "Science Fiction" },
  { value: "parallel-universe", label: "Parallel Universe", category: "Science Fiction" },
  { value: "post-apocalyptic", label: "Post-Apocalyptic", category: "Science Fiction" },
  { value: "apocalyptic", label: "Apocalyptic", category: "Science Fiction" },
  { value: "climate-fiction", label: "Climate Fiction (Cli-Fi)", category: "Science Fiction" },
  { value: "ai-fiction", label: "AI Fiction", category: "Science Fiction" },
  { value: "nanopunk", label: "Nanopunk", category: "Science Fiction" },
  { value: "generation-ship", label: "Generation Ship", category: "Science Fiction" },
  { value: "colonization", label: "Colonization Sci-Fi", category: "Science Fiction" },
  { value: "xenofiction", label: "Xenofiction (Non-Human POV)", category: "Science Fiction" },

  // ── Romance Subgenres ──
  { value: "contemporary-romance", label: "Contemporary Romance", category: "Romance" },
  { value: "historical-romance", label: "Historical Romance", category: "Romance" },
  { value: "regency-romance", label: "Regency Romance", category: "Romance" },
  { value: "victorian-romance", label: "Victorian Romance", category: "Romance" },
  { value: "paranormal-romance", label: "Paranormal Romance", category: "Romance" },
  { value: "dark-romance", label: "Dark Romance", category: "Romance" },
  { value: "enemies-to-lovers", label: "Enemies to Lovers", category: "Romance" },
  { value: "slow-burn", label: "Slow Burn", category: "Romance" },
  { value: "second-chance", label: "Second Chance Romance", category: "Romance" },
  { value: "forbidden-love", label: "Forbidden Love", category: "Romance" },
  { value: "fake-relationship", label: "Fake Relationship", category: "Romance" },
  { value: "marriage-of-convenience", label: "Marriage of Convenience", category: "Romance" },
  { value: "grumpy-sunshine", label: "Grumpy × Sunshine", category: "Romance" },
  { value: "sports-romance", label: "Sports Romance", category: "Romance" },
  { value: "billionaire-romance", label: "Billionaire Romance", category: "Romance" },
  { value: "small-town-romance", label: "Small Town Romance", category: "Romance" },
  { value: "lgbtq-romance", label: "LGBTQ+ Romance", category: "Romance" },
  { value: "poly-romance", label: "Polyamorous Romance", category: "Romance" },
  { value: "romantic-suspense", label: "Romantic Suspense", category: "Romance" },
  { value: "romantic-comedy", label: "Romantic Comedy", category: "Romance" },
  { value: "western-romance", label: "Western Romance", category: "Romance" },
  { value: "inspirational-romance", label: "Inspirational Romance", category: "Romance" },
  { value: "holiday-romance", label: "Holiday Romance", category: "Romance" },
  { value: "age-gap-romance", label: "Age Gap Romance", category: "Romance" },
  { value: "office-romance", label: "Office Romance", category: "Romance" },
  { value: "royal-romance", label: "Royal Romance", category: "Romance" },
  { value: "mafia-romance", label: "Mafia Romance", category: "Romance" },
  { value: "monster-romance", label: "Monster Romance", category: "Romance" },
  { value: "why-choose", label: "Why Choose / Reverse Harem", category: "Romance" },
  { value: "omegaverse", label: "Omegaverse", category: "Romance" },

  // ── Thriller / Mystery Subgenres ──
  { value: "psychological-thriller", label: "Psychological Thriller", category: "Thriller / Mystery" },
  { value: "domestic-thriller", label: "Domestic Thriller", category: "Thriller / Mystery" },
  { value: "legal-thriller", label: "Legal Thriller", category: "Thriller / Mystery" },
  { value: "political-thriller", label: "Political Thriller", category: "Thriller / Mystery" },
  { value: "spy-thriller", label: "Spy Thriller / Espionage", category: "Thriller / Mystery" },
  { value: "techno-thriller", label: "Techno-Thriller", category: "Thriller / Mystery" },
  { value: "medical-thriller", label: "Medical Thriller", category: "Thriller / Mystery" },
  { value: "cozy-mystery", label: "Cozy Mystery", category: "Thriller / Mystery" },
  { value: "police-procedural", label: "Police Procedural", category: "Thriller / Mystery" },
  { value: "detective", label: "Detective / PI", category: "Thriller / Mystery" },
  { value: "locked-room", label: "Locked Room Mystery", category: "Thriller / Mystery" },
  { value: "whodunit", label: "Whodunit", category: "Thriller / Mystery" },
  { value: "hardboiled", label: "Hardboiled", category: "Thriller / Mystery" },
  { value: "serial-killer", label: "Serial Killer", category: "Thriller / Mystery" },
  { value: "heist", label: "Heist / Caper", category: "Thriller / Mystery" },
  { value: "conspiracy", label: "Conspiracy Thriller", category: "Thriller / Mystery" },
  { value: "forensic", label: "Forensic Thriller", category: "Thriller / Mystery" },
  { value: "vigilante", label: "Vigilante Justice", category: "Thriller / Mystery" },

  // ── Horror Subgenres ──
  { value: "cosmic-horror", label: "Cosmic / Lovecraftian Horror", category: "Horror" },
  { value: "body-horror", label: "Body Horror", category: "Horror" },
  { value: "psychological-horror", label: "Psychological Horror", category: "Horror" },
  { value: "supernatural-horror", label: "Supernatural Horror", category: "Horror" },
  { value: "folk-horror", label: "Folk Horror", category: "Horror" },
  { value: "slasher", label: "Slasher", category: "Horror" },
  { value: "survival-horror", label: "Survival Horror", category: "Horror" },
  { value: "haunted-house", label: "Haunted House", category: "Horror" },
  { value: "vampire", label: "Vampire", category: "Horror" },
  { value: "werewolf", label: "Werewolf", category: "Horror" },
  { value: "zombie", label: "Zombie", category: "Horror" },
  { value: "demon", label: "Demon / Possession", category: "Horror" },
  { value: "witch", label: "Witch / Occult", category: "Horror" },
  { value: "creature-feature", label: "Creature Feature", category: "Horror" },
  { value: "splatterpunk", label: "Splatterpunk / Extreme", category: "Horror" },
  { value: "quiet-horror", label: "Quiet Horror", category: "Horror" },
  { value: "eco-horror", label: "Eco-Horror", category: "Horror" },
  { value: "techno-horror", label: "Techno-Horror", category: "Horror" },
  { value: "holiday-horror", label: "Holiday Horror", category: "Horror" },

  // ── Non-Fiction ──
  { value: "memoir", label: "Memoir", category: "Non-Fiction" },
  { value: "autobiography", label: "Autobiography", category: "Non-Fiction" },
  { value: "biography", label: "Biography", category: "Non-Fiction" },
  { value: "self-help", label: "Self-Help", category: "Non-Fiction" },
  { value: "business", label: "Business", category: "Non-Fiction" },
  { value: "personal-development", label: "Personal Development", category: "Non-Fiction" },
  { value: "productivity", label: "Productivity", category: "Non-Fiction" },
  { value: "psychology", label: "Psychology", category: "Non-Fiction" },
  { value: "philosophy", label: "Philosophy", category: "Non-Fiction" },
  { value: "spirituality", label: "Spirituality", category: "Non-Fiction" },
  { value: "religion", label: "Religion", category: "Non-Fiction" },
  { value: "history", label: "History", category: "Non-Fiction" },
  { value: "science", label: "Science", category: "Non-Fiction" },
  { value: "technology", label: "Technology", category: "Non-Fiction" },
  { value: "politics", label: "Politics", category: "Non-Fiction" },
  { value: "true-crime", label: "True Crime", category: "Non-Fiction" },
  { value: "travel", label: "Travel", category: "Non-Fiction" },
  { value: "cookbook", label: "Cookbook / Food", category: "Non-Fiction" },
  { value: "health-wellness", label: "Health & Wellness", category: "Non-Fiction" },
  { value: "parenting", label: "Parenting", category: "Non-Fiction" },
  { value: "education", label: "Education", category: "Non-Fiction" },
  { value: "reference", label: "Reference", category: "Non-Fiction" },
  { value: "essay-collection", label: "Essay Collection", category: "Non-Fiction" },
  { value: "narrative-nonfiction", label: "Narrative Nonfiction", category: "Non-Fiction" },
  { value: "creative-nonfiction", label: "Creative Nonfiction", category: "Non-Fiction" },
  { value: "investigative-journalism", label: "Investigative Journalism", category: "Non-Fiction" },
  { value: "academic", label: "Academic / Textbook", category: "Non-Fiction" },
  { value: "how-to", label: "How-To / Guide", category: "Non-Fiction" },
  { value: "leadership", label: "Leadership", category: "Non-Fiction" },
  { value: "entrepreneurship", label: "Entrepreneurship", category: "Non-Fiction" },
  { value: "finance", label: "Finance / Investing", category: "Non-Fiction" },
  { value: "marketing", label: "Marketing", category: "Non-Fiction" },
  { value: "design", label: "Design", category: "Non-Fiction" },
  { value: "art", label: "Art", category: "Non-Fiction" },
  { value: "music", label: "Music", category: "Non-Fiction" },
  { value: "sports", label: "Sports", category: "Non-Fiction" },
  { value: "nature", label: "Nature / Environment", category: "Non-Fiction" },
  { value: "social-issues", label: "Social Issues", category: "Non-Fiction" },
  { value: "cultural-criticism", label: "Cultural Criticism", category: "Non-Fiction" },
  { value: "humor", label: "Humor / Comedy", category: "Non-Fiction" },
];

// Flattened list for quick lookup
export const ALL_GENRE_VALUES = GENRE_OPTIONS.map((g) => g.value);

// Grouped for dropdown display
export function getGroupedGenres(): Map<string, GenreOption[]> {
  const map = new Map<string, GenreOption[]>();
  for (const g of GENRE_OPTIONS) {
    const group = map.get(g.category) || [];
    group.push(g);
    map.set(g.category, group);
  }
  return map;
}
