/**
 * AUTHORA pricing copy and plan definitions.
 * Used for marketing pricing page and plan comparison.
 */

export const DEFAULT_PLANS = {
  free: {
    name: 'Free',
    valueNote: 'For trying the platform',
    badge: null as string | null,
    monthly_cents: 0,
    yearly_cents: 0,
    lifetime_cents: null as number | null,
    description: 'For trying the platform and starting one book.',
    cta: 'Start Free',
    features: [
      'One book to get started',
      'Full writing editor',
      'Outlining and planning tools',
      'Notes and idea capture',
      'Writing goals and progress tracking',
      'Light AI support when you need it',
      'Basic exports',
      'Accountability prompts',
    ],
  },
  starter: {
    name: 'Starter',
    valueNote: 'For building consistency',
    badge: null as string | null,
    monthly_cents: 1200,
    yearly_cents: 10800,
    lifetime_cents: null as number | null,
    description: 'For writers building consistency and writing more seriously.',
    cta: 'Choose Starter',
    features: [
      'Up to 3 books at once',
      'Full writing editor',
      'Fiction and non-fiction planning',
      'Chapter and manuscript organization',
      'Notes, idea boards, and research vault',
      'Export to DOCX, PDF, EPUB',
      'Writing reminders and streaks',
      'Stronger AI support',
      'Progress tracking and accountability',
    ],
  },
  pro: {
    name: 'Pro',
    valueNote: 'For finishing books',
    monthly_cents: 2400,
    yearly_cents: 21600,
    lifetime_cents: null as number | null,
    description: 'For writers who want to finish books, use stronger AI support, and manage multiple projects properly.',
    cta: 'Go Pro',
    badge: 'Recommended',
    features: [
      'Multiple projects — write as many books as you need',
      'Finish Mode — built to help you actually finish',
      'Story Integrity Engine — find what your story is missing',
      'Story Density Engine — cut filler, strengthen what matters',
      'Stronger AI support — rewrite, expand, get unstuck',
      'Research vault — keep ideas and world-building in one place',
      'Rich exports — DOCX, PDF, EPUB, publishing prep',
      'Collaboration — share with beta readers and co-writers',
      'Deeper accountability and milestones',
    ],
  },
  studio: {
    name: 'Studio',
    valueNote: 'For serious output',
    badge: 'Premium' as string | null,
    monthly_cents: 4900,
    yearly_cents: 46800,
    lifetime_cents: null as number | null,
    description: 'For people who write a lot, publish more, collaborate more, or want the best overall experience.',
    cta: 'Choose Studio',
    features: [
      'Everything in Pro',
      'Highest AI allowance',
      'Best-in-class writing and editing support',
      'Maximum flexibility for multiple projects',
      'Premium collaboration tools',
      'Priority access to new features',
      'For power users and prolific authors',
    ],
  },
  founder_lifetime: {
    name: 'Founder Lifetime',
    valueNote: 'Limited early-adopter offer',
    badge: 'Limited Offer' as string | null,
    monthly_cents: null as number | null,
    yearly_cents: null as number | null,
    lifetime_cents: 34900,
    description: 'A limited early-adopter offer for supporters who want lifetime access.',
    cta: 'Claim Founder Access',
    features: [
      'Lifetime access to core Authora features',
      'Finish Mode and manuscript intelligence',
      'Planning and finishing workflows',
      'AI support with fair-use guidelines',
    ],
  },
} as const;

export type PlanSlug = keyof typeof DEFAULT_PLANS;

export const PLAN_COMPARISON_ROWS: { key: string; label: string }[] = [
  { key: 'active_books', label: 'Multiple projects' },
  { key: 'writing_editor', label: 'Writing editor' },
  { key: 'outlining', label: 'Outlining tools' },
  { key: 'fiction_planning', label: 'Fiction planning' },
  { key: 'nonfiction_planning', label: 'Non-fiction planning' },
  { key: 'notes_research', label: 'Notes and research vault' },
  { key: 'ai_assistance', label: 'AI support' },
  { key: 'ghostwriter', label: 'Ghostwriter tools' },
  { key: 'finish_mode', label: 'Finish Mode' },
  { key: 'export', label: 'Exports' },
  { key: 'progress_tracking', label: 'Progress tracking' },
  { key: 'accountability', label: 'Accountability tools' },
  { key: 'smart_search', label: 'Smart search' },
  { key: 'story_integrity', label: 'Story Integrity Engine' },
  { key: 'story_density', label: 'Story Density Engine' },
  { key: 'premium_ai', label: 'Premium AI' },
  { key: 'collaboration', label: 'Collaboration' },
  { key: 'priority_workflows', label: 'Priority features' },
  { key: 'lifetime', label: 'Lifetime access' },
];

export const PLAN_COMPARISON_MATRIX: Record<
  PlanSlug,
  Record<string, boolean | string>
> = {
  free: {
    active_books: '1',
    writing_editor: true,
    outlining: true,
    fiction_planning: false,
    nonfiction_planning: false,
    notes_research: true,
    ai_assistance: 'Limited',
    ghostwriter: false,
    finish_mode: false,
    export: 'Limited',
    progress_tracking: true,
    accountability: 'Basic',
    smart_search: false,
    story_integrity: false,
    story_density: false,
    premium_ai: false,
    collaboration: false,
    priority_workflows: false,
    lifetime: false,
  },
  starter: {
    active_books: '3',
    writing_editor: true,
    outlining: true,
    fiction_planning: true,
    nonfiction_planning: true,
    notes_research: true,
    ai_assistance: 'Standard',
    ghostwriter: false,
    finish_mode: false,
    export: 'Standard',
    progress_tracking: true,
    accountability: true,
    smart_search: false,
    story_integrity: false,
    story_density: false,
    premium_ai: false,
    collaboration: false,
    priority_workflows: false,
    lifetime: false,
  },
  pro: {
    active_books: 'Unlimited',
    writing_editor: true,
    outlining: true,
    fiction_planning: true,
    nonfiction_planning: true,
    notes_research: true,
    ai_assistance: true,
    ghostwriter: true,
    finish_mode: true,
    export: 'Rich',
    progress_tracking: true,
    accountability: true,
    smart_search: true,
    story_integrity: true,
    story_density: true,
    premium_ai: false,
    collaboration: true,
    priority_workflows: true,
    lifetime: false,
  },
  studio: {
    active_books: 'Unlimited',
    writing_editor: true,
    outlining: true,
    fiction_planning: true,
    nonfiction_planning: true,
    notes_research: true,
    ai_assistance: true,
    ghostwriter: true,
    finish_mode: true,
    export: 'Rich',
    progress_tracking: true,
    accountability: true,
    smart_search: true,
    story_integrity: true,
    story_density: true,
    premium_ai: true,
    collaboration: true,
    priority_workflows: true,
    lifetime: false,
  },
  founder_lifetime: {
    active_books: 'Unlimited',
    writing_editor: true,
    outlining: true,
    fiction_planning: true,
    nonfiction_planning: true,
    notes_research: true,
    ai_assistance: true,
    ghostwriter: true,
    finish_mode: true,
    export: 'Standard',
    progress_tracking: true,
    accountability: true,
    smart_search: true,
    story_integrity: true,
    story_density: true,
    premium_ai: false,
    collaboration: true,
    priority_workflows: false,
    lifetime: true,
  },
};
