/**
 * AUTHORA pricing copy and plan definitions.
 * Used for marketing pricing page and plan comparison.
 */

export const DEFAULT_PLANS = {
  free: {
    name: 'Free',
    valueNote: 'Get started and explore',
    badge: null as string | null,
    monthly_cents: 0,
    yearly_cents: 0,
    lifetime_cents: null as number | null,
    description: 'Basic writing, light AI, and starter templates. Perfect for trying Authora.',
    cta: 'Start Free',
    features: [
      'Basic writing and organization',
      'One book to get started',
      'Limited AI when you need a nudge',
      'Starter templates',
      'Notes and idea capture',
      'Writing goals and progress',
      'Basic exports',
    ],
  },
  starter: {
    name: 'Starter',
    valueNote: 'For building consistency',
    badge: null as string | null,
    monthly_cents: 1200,
    yearly_cents: 10800,
    lifetime_cents: null as number | null,
    description: 'For writers building consistency and writing more seriously.',
    cta: 'Choose Starter',
    features: [
      'Up to 3 books at once',
      'Full writing editor',
      'Fiction and non-fiction planning',
      'Chapter and manuscript organization',
      'Notes, idea boards, and research vault',
      'Export to DOCX, PDF, EPUB',
      'Writing reminders and streaks',
      'Stronger AI support',
      'Progress tracking and accountability',
    ],
  },
  pro: {
    name: 'Pro',
    valueNote: 'Finish your books',
    monthly_cents: 2400,
    yearly_cents: 21600,
    lifetime_cents: null as number | null,
    description: 'Full writing system with story guidance, AI assistance, and everything you need to finish.',
    cta: 'Go Pro',
    badge: 'Recommended',
    features: [
      'Full writing system — write as many books as you need',
      'Story guidance — find what your story is missing',
      'AI assistance — rewrite, expand, get unstuck',
      'Full template library — fiction, nonfiction, poetry, and more',
      'Export to DOCX, PDF, EPUB',
      'Research vault — ideas and world-building in one place',
      'Collaboration — share with beta readers and co-writers',
      'Deeper accountability and milestones',
    ],
  },
  studio: {
    name: 'Studio',
    valueNote: 'For academic and serious writers',
    badge: 'Premium' as string | null,
    monthly_cents: 4900,
    yearly_cents: 46800,
    lifetime_cents: null as number | null,
    description: 'Everything in Pro, plus citation tools, academic templates for students, teachers, and lecturers, originality review, and AI insights.',
    cta: 'Choose Studio',
    features: [
      'Everything in Pro',
      'Citation system — add and manage references',
      'Bibliography tools — build and format your sources',
      'Academic templates — essays, exams, courses, and lecture materials for students, teachers, lecturers',
      'Originality review — similarity and AI-assistance transparency',
      'AI insights — see where AI helped, review with confidence',
      'Premium features — highest AI allowance, priority support',
    ],
  },
} as const;

export type PlanSlug = keyof typeof DEFAULT_PLANS;

export const PLAN_COMPARISON_ROWS: { key: string; label: string }[] = [
  { key: 'active_books', label: 'Multiple projects' },
  { key: 'writing_editor', label: 'Writing editor' },
  { key: 'outlining', label: 'Outlining tools' },
  { key: 'fiction_planning', label: 'Fiction planning' },
  { key: 'nonfiction_planning', label: 'Non-fiction planning' },
  { key: 'notes_research', label: 'Notes and research vault' },
  { key: 'ai_assistance', label: 'AI support' },
  { key: 'templates', label: 'Templates' },
  { key: 'ghostwriter', label: 'Ghostwriter tools' },
  { key: 'finish_mode', label: 'Finish Mode' },
  { key: 'export', label: 'Exports' },
  { key: 'progress_tracking', label: 'Progress tracking' },
  { key: 'accountability', label: 'Accountability tools' },
  { key: 'smart_search', label: 'Smart search' },
  { key: 'story_integrity', label: 'Story Integrity Engine' },
  { key: 'story_density', label: 'Story Density Engine' },
  { key: 'citation_system', label: 'Citation system' },
  { key: 'bibliography', label: 'Bibliography tools' },
  { key: 'academic_templates', label: 'Academic templates (essays, exams, courses)' },
  { key: 'originality_review', label: 'Originality review' },
  { key: 'ai_insights', label: 'AI insights and transparency' },
  { key: 'premium_ai', label: 'Premium AI' },
  { key: 'collaboration', label: 'Collaboration' },
  { key: 'priority_workflows', label: 'Priority features' },
  { key: 'lifetime', label: 'Lifetime access' },
];

export const PLAN_COMPARISON_MATRIX: Record<
  PlanSlug,
  Record<string, boolean | string>
> = {
  free: {
    active_books: '1',
    writing_editor: true,
    outlining: true,
    fiction_planning: false,
    nonfiction_planning: false,
    notes_research: true,
    ai_assistance: 'Limited',
    templates: 'Starter',
    ghostwriter: false,
    finish_mode: false,
    export: 'Limited',
    progress_tracking: true,
    accountability: 'Basic',
    smart_search: false,
    story_integrity: false,
    story_density: false,
    citation_system: false,
    bibliography: false,
    academic_templates: false,
    originality_review: false,
    ai_insights: false,
    premium_ai: false,
    collaboration: false,
    priority_workflows: false,
    lifetime: false,
  },
  starter: {
    active_books: '3',
    writing_editor: true,
    outlining: true,
    fiction_planning: true,
    nonfiction_planning: true,
    notes_research: true,
    ai_assistance: 'Standard',
    templates: true,
    ghostwriter: false,
    finish_mode: false,
    export: 'Standard',
    progress_tracking: true,
    accountability: true,
    smart_search: false,
    story_integrity: false,
    story_density: false,
    citation_system: false,
    bibliography: false,
    academic_templates: false,
    originality_review: false,
    ai_insights: false,
    premium_ai: false,
    collaboration: false,
    priority_workflows: false,
    lifetime: false,
  },
  pro: {
    active_books: 'Unlimited',
    writing_editor: true,
    outlining: true,
    fiction_planning: true,
    nonfiction_planning: true,
    notes_research: true,
    ai_assistance: true,
    templates: true,
    ghostwriter: true,
    finish_mode: true,
    export: 'Rich',
    progress_tracking: true,
    accountability: true,
    smart_search: true,
    story_integrity: true,
    story_density: true,
    citation_system: false,
    bibliography: false,
    academic_templates: false,
    originality_review: false,
    ai_insights: false,
    premium_ai: false,
    collaboration: true,
    priority_workflows: true,
    lifetime: false,
  },
  studio: {
    active_books: 'Unlimited',
    writing_editor: true,
    outlining: true,
    fiction_planning: true,
    nonfiction_planning: true,
    notes_research: true,
    ai_assistance: true,
    templates: true,
    ghostwriter: true,
    finish_mode: true,
    export: 'Rich',
    progress_tracking: true,
    accountability: true,
    smart_search: true,
    story_integrity: true,
    story_density: true,
    citation_system: true,
    bibliography: true,
    academic_templates: true,
    originality_review: true,
    ai_insights: true,
    premium_ai: true,
    collaboration: true,
    priority_workflows: true,
    lifetime: false,
  },
};

