// Comprehensive themes list for fiction and creative non-fiction.
// Grouped by category for the dropdown UI.

export interface ThemeOption {
  value: string;
  label: string;
  category: string;
}

export const THEME_OPTIONS: ThemeOption[] = [
  // ── World & Setting ──
  { value: "dystopian", label: "Dystopian", category: "World & Setting" },
  { value: "utopian", label: "Utopian", category: "World & Setting" },
  { value: "post-apocalyptic", label: "Post-Apocalyptic", category: "World & Setting" },
  { value: "apocalyptic", label: "Apocalyptic", category: "World & Setting" },
  { value: "pre-apocalyptic", label: "Pre-Apocalyptic", category: "World & Setting" },
  { value: "cyberpunk", label: "Cyberpunk", category: "World & Setting" },
  { value: "steampunk", label: "Steampunk", category: "World & Setting" },
  { value: "solarpunk", label: "Solarpunk", category: "World & Setting" },
  { value: "dieselpunk", label: "Dieselpunk", category: "World & Setting" },
  { value: "medieval", label: "Medieval", category: "World & Setting" },
  { value: "ancient-world", label: "Ancient World", category: "World & Setting" },
  { value: "renaissance", label: "Renaissance", category: "World & Setting" },
  { value: "victorian", label: "Victorian Era", category: "World & Setting" },
  { value: "regency", label: "Regency Era", category: "World & Setting" },
  { value: "edwardian", label: "Edwardian Era", category: "World & Setting" },
  { value: "world-war-one", label: "World War I", category: "World & Setting" },
  { value: "world-war-two", label: "World War II", category: "World & Setting" },
  { value: "cold-war", label: "Cold War", category: "World & Setting" },
  { value: "modern-day", label: "Modern Day", category: "World & Setting" },
  { value: "near-future", label: "Near Future", category: "World & Setting" },
  { value: "far-future", label: "Far Future", category: "World & Setting" },
  { value: "alternate-history", label: "Alternate History", category: "World & Setting" },
  { value: "parallel-universe", label: "Parallel Universe", category: "World & Setting" },
  { value: "virtual-reality", label: "Virtual Reality", category: "World & Setting" },
  { value: "dream-world", label: "Dream World", category: "World & Setting" },
  { value: "underworld", label: "Underworld / Hell", category: "World & Setting" },
  { value: "heaven", label: "Heaven / Afterlife", category: "World & Setting" },
  { value: "space", label: "Space / Interstellar", category: "World & Setting" },
  { value: "ocean", label: "Ocean / Underwater", category: "World & Setting" },
  { value: "underground", label: "Underground", category: "World & Setting" },
  { value: "isolated-community", label: "Isolated Community", category: "World & Setting" },
  { value: "small-town", label: "Small Town", category: "World & Setting" },
  { value: "big-city", label: "Big City", category: "World & Setting" },
  { value: "suburban", label: "Suburban", category: "World & Setting" },
  { value: "rural", label: "Rural / Countryside", category: "World & Setting" },
  { value: "wilderness", label: "Wilderness", category: "World & Setting" },
  { value: "desert", label: "Desert", category: "World & Setting" },
  { value: "arctic", label: "Arctic / Frozen", category: "World & Setting" },
  { value: "jungle", label: "Jungle", category: "World & Setting" },
  { value: "prison", label: "Prison / Captivity", category: "World & Setting" },
  { value: "academy", label: "Academy / School", category: "World & Setting" },
  { value: "royal-court", label: "Royal Court", category: "World & Setting" },
  { value: "military", label: "Military / War", category: "World & Setting" },
  { value: "corporate", label: "Corporate / Workplace", category: "World & Setting" },
  { value: "criminal-underworld", label: "Criminal Underworld", category: "World & Setting" },
  { value: "asylum", label: "Asylum / Institution", category: "World & Setting" },
  { value: "circus", label: "Circus / Carnival", category: "World & Setting" },
  { value: "frontier", label: "Frontier / Wild West", category: "World & Setting" },
  { value: "colonial", label: "Colonial Era", category: "World & Setting" },
  { value: "golden-age", label: "Golden Age", category: "World & Setting" },
  { value: "dark-ages", label: "Dark Ages", category: "World & Setting" },
  { value: "lost-civilization", label: "Lost Civilization", category: "World & Setting" },
  { value: "hidden-world", label: "Hidden World", category: "World & Setting" },
  { value: "pocket-dimension", label: "Pocket Dimension", category: "World & Setting" },
  { value: "multiverse", label: "Multiverse", category: "World & Setting" },

  // ── Relationships ──
  { value: "forbidden-love", label: "Forbidden Love", category: "Relationships" },
  { value: "enemies-to-lovers", label: "Enemies to Lovers", category: "Relationships" },
  { value: "friends-to-lovers", label: "Friends to Lovers", category: "Relationships" },
  { value: "second-chance", label: "Second Chance", category: "Relationships" },
  { value: "star-crossed", label: "Star-Crossed Lovers", category: "Relationships" },
  { value: "love-triangle", label: "Love Triangle", category: "Relationships" },
  { value: "unrequited-love", label: "Unrequited Love", category: "Relationships" },
  { value: "slow-burn", label: "Slow Burn Romance", category: "Relationships" },
  { value: "soulmates", label: "Soulmates / Fated", category: "Relationships" },
  { value: "marriage", label: "Marriage", category: "Relationships" },
  { value: "divorce", label: "Divorce / Separation", category: "Relationships" },
  { value: "found-family", label: "Found Family", category: "Relationships" },
  { value: "family-drama", label: "Family Drama", category: "Relationships" },
  { value: "dysfunctional-family", label: "Dysfunctional Family", category: "Relationships" },
  { value: "sibling-rivalry", label: "Sibling Rivalry", category: "Relationships" },
  { value: "parent-child", label: "Parent-Child Bond", category: "Relationships" },
  { value: "absent-parent", label: "Absent Parent", category: "Relationships" },
  { value: "orphan", label: "Orphan / Abandoned", category: "Relationships" },
  { value: "adoption", label: "Adoption", category: "Relationships" },
  { value: "friendship", label: "Friendship", category: "Relationships" },
  { value: "betrayal", label: "Betrayal", category: "Relationships" },
  { value: "loyalty", label: "Loyalty", category: "Relationships" },
  { value: "rivalry", label: "Rivalry", category: "Relationships" },
  { value: "mentor-student", label: "Mentor / Student", category: "Relationships" },
  { value: "master-apprentice", label: "Master / Apprentice", category: "Relationships" },
  { value: "chosen-family", label: "Chosen Family", category: "Relationships" },
  { value: "community", label: "Community", category: "Relationships" },
  { value: "isolation", label: "Isolation / Loneliness", category: "Relationships" },
  { value: "belonging", label: "Belonging", category: "Relationships" },
  { value: "outsider", label: "Outsider", category: "Relationships" },
  { value: "redemption", label: "Redemption", category: "Relationships" },
  { value: "forgiveness", label: "Forgiveness", category: "Relationships" },
  { value: "reconciliation", label: "Reconciliation", category: "Relationships" },
  { value: "toxic-relationship", label: "Toxic Relationship", category: "Relationships" },
  { value: "abuse-survival", label: "Abuse Survival", category: "Relationships" },
  { value: "grief", label: "Grief / Loss", category: "Relationships" },
  { value: "healing", label: "Healing", category: "Relationships" },
  { value: "letting-go", label: "Letting Go", category: "Relationships" },
  { value: "moving-on", label: "Moving On", category: "Relationships" },
  { value: "sacrifice", label: "Sacrifice", category: "Relationships" },
  { value: "devotion", label: "Devotion", category: "Relationships" },
  { value: "obsession", label: "Obsession", category: "Relationships" },
  { value: "jealousy", label: "Jealousy", category: "Relationships" },
  { value: "trust", label: "Trust", category: "Relationships" },
  { value: "secrets", label: "Secrets", category: "Relationships" },
  { value: "lies", label: "Lies / Deception", category: "Relationships" },

  // ── Identity & Self ──
  { value: "coming-of-age", label: "Coming of Age", category: "Identity & Self" },
  { value: "self-discovery", label: "Self-Discovery", category: "Identity & Self" },
  { value: "identity", label: "Identity", category: "Identity & Self" },
  { value: "transformation", label: "Transformation", category: "Identity & Self" },
  { value: "metamorphosis", label: "Metamorphosis", category: "Identity & Self" },
  { value: "duality", label: "Duality / Double Life", category: "Identity & Self" },
  { value: "imposter-syndrome", label: "Imposter Syndrome", category: "Identity & Self" },
  { value: "self-worth", label: "Self-Worth", category: "Identity & Self" },
  { value: "self-destruction", label: "Self-Destruction", category: "Identity & Self" },
  { value: "addiction", label: "Addiction", category: "Identity & Self" },
  { value: "recovery", label: "Recovery", category: "Identity & Self" },
  { value: "mental-health", label: "Mental Health", category: "Identity & Self" },
  { value: "trauma", label: "Trauma", category: "Identity & Self" },
  { value: "ptsd", label: "PTSD", category: "Identity & Self" },
  { value: "madness", label: "Madness / Sanity", category: "Identity & Self" },
  { value: "memory", label: "Memory", category: "Identity & Self" },
  { value: "amnesia", label: "Amnesia", category: "Identity & Self" },
  { value: "dreams", label: "Dreams", category: "Identity & Self" },
  { value: "nightmares", label: "Nightmares", category: "Identity & Self" },
  { value: "fate", label: "Fate / Destiny", category: "Identity & Self" },
  { value: "free-will", label: "Free Will", category: "Identity & Self" },
  { value: "choice", label: "Choice / Consequence", category: "Identity & Self" },
  { value: "purpose", label: "Purpose / Meaning", category: "Identity & Self" },
  { value: "legacy", label: "Legacy", category: "Identity & Self" },
  { value: "mortality", label: "Mortality", category: "Identity & Self" },
  { value: "immortality", label: "Immortality", category: "Identity & Self" },
  { value: "aging", label: "Aging", category: "Identity & Self" },
  { value: "youth", label: "Youth", category: "Identity & Self" },
  { value: "innocence", label: "Innocence", category: "Identity & Self" },
  { value: "loss-of-innocence", label: "Loss of Innocence", category: "Identity & Self" },
  { value: "courage", label: "Courage", category: "Identity & Self" },
  { value: "fear", label: "Fear", category: "Identity & Self" },
  { value: "guilt", label: "Guilt", category: "Identity & Self" },
  { value: "shame", label: "Shame", category: "Identity & Self" },
  { value: "pride", label: "Pride", category: "Identity & Self" },
  { value: "ambition", label: "Ambition", category: "Identity & Self" },
  { value: "perfectionism", label: "Perfectionism", category: "Identity & Self" },
  { value: "failure", label: "Failure", category: "Identity & Self" },
  { value: "resilience", label: "Resilience", category: "Identity & Self" },
  { value: "survival", label: "Survival", category: "Identity & Self" },
  { value: "perseverance", label: "Perseverance", category: "Identity & Self" },
  { value: "hope", label: "Hope", category: "Identity & Self" },
  { value: "despair", label: "Despair", category: "Identity & Self" },
  { value: "faith", label: "Faith", category: "Identity & Self" },
  { value: "doubt", label: "Doubt", category: "Identity & Self" },
  { value: "belief", label: "Belief", category: "Identity & Self" },
  { value: "disillusionment", label: "Disillusionment", category: "Identity & Self" },
  { value: "awakening", label: "Awakening", category: "Identity & Self" },
  { value: "enlightenment", label: "Enlightenment", category: "Identity & Self" },
  { value: "gender-identity", label: "Gender Identity", category: "Identity & Self" },
  { value: "sexuality", label: "Sexuality", category: "Identity & Self" },
  { value: "body-image", label: "Body Image", category: "Identity & Self" },
  { value: "disability", label: "Disability", category: "Identity & Self" },
  { value: "neurodivergence", label: "Neurodivergence", category: "Identity & Self" },

  // ── Power & Society ──
  { value: "power", label: "Power", category: "Power & Society" },
  { value: "corruption", label: "Corruption", category: "Power & Society" },
  { value: "revolution", label: "Revolution", category: "Power & Society" },
  { value: "rebellion", label: "Rebellion", category: "Power & Society" },
  { value: "resistance", label: "Resistance", category: "Power & Society" },
  { value: "oppression", label: "Oppression", category: "Power & Society" },
  { value: "tyranny", label: "Tyranny", category: "Power & Society" },
  { value: "totalitarianism", label: "Totalitarianism", category: "Power & Society" },
  { value: "freedom", label: "Freedom", category: "Power & Society" },
  { value: "liberty", label: "Liberty", category: "Power & Society" },
  { value: "justice", label: "Justice", category: "Power & Society" },
  { value: "injustice", label: "Injustice", category: "Power & Society" },
  { value: "inequality", label: "Inequality", category: "Power & Society" },
  { value: "class-struggle", label: "Class Struggle", category: "Power & Society" },
  { value: "poverty", label: "Poverty", category: "Power & Society" },
  { value: "wealth", label: "Wealth", category: "Power & Society" },
  { value: "privilege", label: "Privilege", category: "Power & Society" },
  { value: "social-mobility", label: "Social Mobility", category: "Power & Society" },
  { value: "propaganda", label: "Propaganda", category: "Power & Society" },
  { value: "censorship", label: "Censorship", category: "Power & Society" },
  { value: "surveillance", label: "Surveillance", category: "Power & Society" },
  { value: "conspiracy", label: "Conspiracy", category: "Power & Society" },
  { value: "secret-society", label: "Secret Society", category: "Power & Society" },
  { value: "anarchy", label: "Anarchy", category: "Power & Society" },
  { value: "order-vs-chaos", label: "Order vs Chaos", category: "Power & Society" },
  { value: "civilization", label: "Civilization", category: "Power & Society" },
  { value: "colonialism", label: "Colonialism", category: "Power & Society" },
  { value: "imperialism", label: "Imperialism", category: "Power & Society" },
  { value: "war", label: "War", category: "Power & Society" },
  { value: "peace", label: "Peace", category: "Power & Society" },
  { value: "genocide", label: "Genocide", category: "Power & Society" },
  { value: "refugee", label: "Refugee / Displacement", category: "Power & Society" },
  { value: "immigration", label: "Immigration", category: "Power & Society" },
  { value: "exile", label: "Exile", category: "Power & Society" },
  { value: "borders", label: "Borders", category: "Power & Society" },
  { value: "nationalism", label: "Nationalism", category: "Power & Society" },
  { value: "patriotism", label: "Patriotism", category: "Power & Society" },
  { value: "propaganda", label: "Propaganda", category: "Power & Society" },
  { value: "media-manipulation", label: "Media Manipulation", category: "Power & Society" },
  { value: "fake-news", label: "Fake News / Misinformation", category: "Power & Society" },
  { value: "activism", label: "Activism", category: "Power & Society" },
  { value: "civil-rights", label: "Civil Rights", category: "Power & Society" },
  { value: "feminism", label: "Feminism", category: "Power & Society" },
  { value: "racism", label: "Racism", category: "Power & Society" },
  { value: "xenophobia", label: "Xenophobia", category: "Power & Society" },
  { value: "discrimination", label: "Discrimination", category: "Power & Society" },
  { value: "prejudice", label: "Prejudice", category: "Power & Society" },
  { value: "tolerance", label: "Tolerance", category: "Power & Society" },
  { value: "diversity", label: "Diversity", category: "Power & Society" },
  { value: "inclusion", label: "Inclusion", category: "Power & Society" },
  { value: "assimilation", label: "Assimilation", category: "Power & Society" },
  { value: "cultural-identity", label: "Cultural Identity", category: "Power & Society" },
  { value: "tradition", label: "Tradition", category: "Power & Society" },
  { value: "progress", label: "Progress", category: "Power & Society" },
  { value: "change", label: "Change", category: "Power & Society" },
  { value: "status-quo", label: "Status Quo", category: "Power & Society" },
  { value: "utilitarianism", label: "Utilitarianism", category: "Power & Society" },
  { value: "greater-good", label: "The Greater Good", category: "Power & Society" },
  { value: "ends-justify-means", label: "Ends Justify Means", category: "Power & Society" },
  { value: "moral-ambiguity", label: "Moral Ambiguity", category: "Power & Society" },
  { value: "gray-morality", label: "Gray Morality", category: "Power & Society" },

  // ── Knowledge & Truth ──
  { value: "truth", label: "Truth", category: "Knowledge & Truth" },
  { value: "knowledge", label: "Knowledge", category: "Knowledge & Truth" },
  { value: "ignorance", label: "Ignorance", category: "Knowledge & Truth" },
  { value: "wisdom", label: "Wisdom", category: "Knowledge & Truth" },
  { value: "discovery", label: "Discovery", category: "Knowledge & Truth" },
  { value: "exploration", label: "Exploration", category: "Knowledge & Truth" },
  { value: "curiosity", label: "Curiosity", category: "Knowledge & Truth" },
  { value: "mystery", label: "Mystery", category: "Knowledge & Truth" },
  { value: "secret", label: "Secrets", category: "Knowledge & Truth" },
  { value: "revelation", label: "Revelation", category: "Knowledge & Truth" },
  { value: "perception", label: "Perception", category: "Knowledge & Truth" },
  { value: "reality", label: "Reality", category: "Knowledge & Truth" },
  { value: "illusion", label: "Illusion", category: "Knowledge & Truth" },
  { value: "unreliable-narrator", label: "Unreliable Narrator", category: "Knowledge & Truth" },
  { value: "perspective", label: "Perspective", category: "Knowledge & Truth" },
  { value: "subjectivity", label: "Subjectivity", category: "Knowledge & Truth" },
  { value: "objectivity", label: "Objectivity", category: "Knowledge & Truth" },
  { value: "science", label: "Science", category: "Knowledge & Truth" },
  { value: "technology", label: "Technology", category: "Knowledge & Truth" },
  { value: "artificial-intelligence", label: "Artificial Intelligence", category: "Knowledge & Truth" },
  { value: "consciousness", label: "Consciousness", category: "Knowledge & Truth" },
  { value: "sentience", label: "Sentience", category: "Knowledge & Truth" },
  { value: "transhumanism", label: "Transhumanism", category: "Knowledge & Truth" },
  { value: "evolution", label: "Evolution", category: "Knowledge & Truth" },
  { value: "creation", label: "Creation", category: "Knowledge & Truth" },
  { value: "nature-vs-nurture", label: "Nature vs Nurture", category: "Knowledge & Truth" },
  { value: "education", label: "Education", category: "Knowledge & Truth" },
  { value: "language", label: "Language", category: "Knowledge & Truth" },
  { value: "communication", label: "Communication", category: "Knowledge & Truth" },
  { value: "storytelling", label: "Storytelling", category: "Knowledge & Truth" },
  { value: "history", label: "History", category: "Knowledge & Truth" },
  { value: "myth", label: "Myth", category: "Knowledge & Truth" },
  { value: "prophecy", label: "Prophecy", category: "Knowledge & Truth" },
  { value: "forbidden-knowledge", label: "Forbidden Knowledge", category: "Knowledge & Truth" },
  { value: "lost-knowledge", label: "Lost Knowledge", category: "Knowledge & Truth" },
  { value: "ancient-secrets", label: "Ancient Secrets", category: "Knowledge & Truth" },
  { value: "conspiracy", label: "Conspiracy", category: "Knowledge & Truth" },
  { value: "cover-up", label: "Cover-Up", category: "Knowledge & Truth" },
  { value: "whistleblower", label: "Whistleblower", category: "Knowledge & Truth" },

  // ── Life & Death ──
  { value: "life", label: "Life", category: "Life & Death" },
  { value: "death", label: "Death", category: "Life & Death" },
  { value: "rebirth", label: "Rebirth", category: "Life & Death" },
  { value: "resurrection", label: "Resurrection", category: "Life & Death" },
  { value: "afterlife", label: "Afterlife", category: "Life & Death" },
  { value: "reincarnation", label: "Reincarnation", category: "Life & Death" },
  { value: "ghosts", label: "Ghosts / Spirits", category: "Life & Death" },
  { value: "undead", label: "Undead", category: "Life & Death" },
  { value: "vampirism", label: "Vampirism", category: "Life & Death" },
  { value: "immortality", label: "Immortality", category: "Life & Death" },
  { value: "mortality", label: "Mortality", category: "Life & Death" },
  { value: "terminal-illness", label: "Terminal Illness", category: "Life & Death" },
  { value: "suicide", label: "Suicide", category: "Life & Death" },
  { value: "murder", label: "Murder", category: "Life & Death" },
  { value: "sacrifice", label: "Sacrifice", category: "Life & Death" },
  { value: "martyrdom", label: "Martyrdom", category: "Life & Death" },
  { value: "legacy", label: "Legacy", category: "Life & Death" },
  { value: "aftermath", label: "Aftermath", category: "Life & Death" },
  { value: "survival", label: "Survival", category: "Life & Death" },
  { value: "near-death", label: "Near-Death Experience", category: "Life & Death" },
  { value: "fragility", label: "Fragility of Life", category: "Life & Death" },
  { value: "circle-of-life", label: "Circle of Life", category: "Life & Death" },
  { value: "ancestors", label: "Ancestors", category: "Life & Death" },
  { value: "descendants", label: "Descendants", category: "Life & Death" },
  { value: "generations", label: "Generations", category: "Life & Death" },
  { value: "inheritance", label: "Inheritance", category: "Life & Death" },
  { value: "birthright", label: "Birthright", category: "Life & Death" },
  { value: "bloodline", label: "Bloodline", category: "Life & Death" },
  { value: "curse", label: "Curse", category: "Life & Death" },
  { value: "blessing", label: "Blessing", category: "Life & Death" },

  // ── Good vs Evil ──
  { value: "good-vs-evil", label: "Good vs Evil", category: "Good vs Evil" },
  { value: "heroism", label: "Heroism", category: "Good vs Evil" },
  { value: "villainy", label: "Villainy", category: "Good vs Evil" },
  { value: "anti-hero", label: "Anti-Hero", category: "Good vs Evil" },
  { value: "sympathetic-villain", label: "Sympathetic Villain", category: "Good vs Evil" },
  { value: "fall-from-grace", label: "Fall from Grace", category: "Good vs Evil" },
  { value: "redemption-arc", label: "Redemption Arc", category: "Good vs Evil" },
  { value: "corruption-arc", label: "Corruption Arc", category: "Good vs Evil" },
  { value: "temptation", label: "Temptation", category: "Good vs Evil" },
  { value: "sin", label: "Sin", category: "Good vs Evil" },
  { value: "virtue", label: "Virtue", category: "Good vs Evil" },
  { value: "morality", label: "Morality", category: "Good vs Evil" },
  { value: "ethics", label: "Ethics", category: "Good vs Evil" },
  { value: "conscience", label: "Conscience", category: "Good vs Evil" },
  { value: "inner-demons", label: "Inner Demons", category: "Good vs Evil" },
  { value: "dark-side", label: "Dark Side", category: "Good vs Evil" },
  { value: "light-vs-dark", label: "Light vs Dark", category: "Good vs Evil" },
  { value: "duality", label: "Duality of Man", category: "Good vs Evil" },
  { value: "monster-within", label: "Monster Within", category: "Good vs Evil" },
  { value: "human-nature", label: "Human Nature", category: "Good vs Evil" },
  { value: "original-sin", label: "Original Sin", category: "Good vs Evil" },
  { value: "atonement", label: "Atonement", category: "Good vs Evil" },
  { value: "penance", label: "Penance", category: "Good vs Evil" },
  { value: "karma", label: "Karma", category: "Good vs Evil" },
  { value: "cosmic-justice", label: "Cosmic Justice", category: "Good vs Evil" },
  { value: "divine-intervention", label: "Divine Intervention", category: "Good vs Evil" },
  { value: "demonic-pact", label: "Demonic Pact", category: "Good vs Evil" },
  { value: "faustian-bargain", label: "Faustian Bargain", category: "Good vs Evil" },
  { value: "deal-with-the-devil", label: "Deal with the Devil", category: "Good vs Evil" },
  { value: "price-of-power", label: "Price of Power", category: "Good vs Evil" },

  // ── Nature & Environment ──
  { value: "nature", label: "Nature", category: "Nature & Environment" },
  { value: "environment", label: "Environment", category: "Nature & Environment" },
  { value: "climate-change", label: "Climate Change", category: "Nature & Environment" },
  { value: "ecological-collapse", label: "Ecological Collapse", category: "Nature & Environment" },
  { value: "conservation", label: "Conservation", category: "Nature & Environment" },
  { value: "man-vs-nature", label: "Man vs Nature", category: "Nature & Environment" },
  { value: "natural-disaster", label: "Natural Disaster", category: "Nature & Environment" },
  { value: "pandemic", label: "Pandemic / Plague", category: "Nature & Environment" },
  { value: "extinction", label: "Extinction", category: "Nature & Environment" },
  { value: "evolution", label: "Evolution", category: "Nature & Environment" },
  { value: "adaptation", label: "Adaptation", category: "Nature & Environment" },
  { value: "symbiosis", label: "Symbiosis", category: "Nature & Environment" },
  { value: "ecosystem", label: "Ecosystem", category: "Nature & Environment" },
  { value: "wilderness", label: "Wilderness", category: "Nature & Environment" },
  { value: "garden", label: "Garden / Cultivation", category: "Nature & Environment" },
  { value: "seasons", label: "Seasons", category: "Nature & Environment" },
  { value: "elements", label: "Elements (Fire/Water/Earth/Air)", category: "Nature & Environment" },
  { value: "animals", label: "Animals", category: "Nature & Environment" },
  { value: "beasts", label: "Beasts / Monsters", category: "Nature & Environment" },
  { value: "dragons", label: "Dragons", category: "Nature & Environment" },
  { value: "shapeshifters", label: "Shapeshifters", category: "Nature & Environment" },
  { value: "hybrids", label: "Hybrids / Chimeras", category: "Nature & Environment" },
  { value: "mutations", label: "Mutations", category: "Nature & Environment" },
  { value: "genetic-engineering", label: "Genetic Engineering", category: "Nature & Environment" },
  { value: "bioethics", label: "Bioethics", category: "Nature & Environment" },

  // ── Magic & Supernatural ──
  { value: "magic", label: "Magic", category: "Magic & Supernatural" },
  { value: "magic-system", label: "Magic System", category: "Magic & Supernatural" },
  { value: "sorcery", label: "Sorcery", category: "Magic & Supernatural" },
  { value: "witchcraft", label: "Witchcraft", category: "Magic & Supernatural" },
  { value: "alchemy", label: "Alchemy", category: "Magic & Supernatural" },
  { value: "necromancy", label: "Necromancy", category: "Magic & Supernatural" },
  { value: "divination", label: "Divination", category: "Magic & Supernatural" },
  { value: "enchantment", label: "Enchantment", category: "Magic & Supernatural" },
  { value: "cursed-object", label: "Cursed Object", category: "Magic & Supernatural" },
  { value: "artifact", label: "Artifact / Relic", category: "Magic & Supernatural" },
  { value: "supernatural", label: "Supernatural", category: "Magic & Supernatural" },
  { value: "paranormal", label: "Paranormal", category: "Magic & Supernatural" },
  { value: "psychic", label: "Psychic / ESP", category: "Magic & Supernatural" },
  { value: "telepathy", label: "Telepathy", category: "Magic & Supernatural" },
  { value: "telekinesis", label: "Telekinesis", category: "Magic & Supernatural" },
  { value: "precognition", label: "Precognition", category: "Magic & Supernatural" },
  { value: "astral-projection", label: "Astral Projection", category: "Magic & Supernatural" },
  { value: "possession", label: "Possession", category: "Magic & Supernatural" },
  { value: "exorcism", label: "Exorcism", category: "Magic & Supernatural" },
  { value: "ritual", label: "Ritual", category: "Magic & Supernatural" },
  { value: "summoning", label: "Summoning", category: "Magic & Supernatural" },
  { value: "binding", label: "Binding", category: "Magic & Supernatural" },
  { value: "banishment", label: "Banishment", category: "Magic & Supernatural" },
  { value: "wards", label: "Wards / Protection", category: "Magic & Supernatural" },
  { value: "ley-lines", label: "Ley Lines", category: "Magic & Supernatural" },
  { value: "portals", label: "Portals / Gateways", category: "Magic & Supernatural" },
  { value: "otherworld", label: "Otherworld / Faerie", category: "Magic & Supernatural" },
  { value: "spirit-world", label: "Spirit World", category: "Magic & Supernatural" },
  { value: "shadow-realm", label: "Shadow Realm", category: "Magic & Supernatural" },
  { value: "chosen-one", label: "Chosen One", category: "Magic & Supernatural" },
  { value: "prophecy", label: "Prophecy", category: "Magic & Supernatural" },
  { value: "destiny", label: "Destiny", category: "Magic & Supernatural" },
  { value: "oracle", label: "Oracle", category: "Magic & Supernatural" },
  { value: "gods", label: "Gods / Deities", category: "Magic & Supernatural" },
  { value: "pantheon", label: "Pantheon", category: "Magic & Supernatural" },
  { value: "demigod", label: "Demigod", category: "Magic & Supernatural" },
  { value: "angels", label: "Angels", category: "Magic & Supernatural" },
  { value: "demons", label: "Demons", category: "Magic & Supernatural" },
  { value: "fae", label: "Fae / Fair Folk", category: "Magic & Supernatural" },
  { value: "elves", label: "Elves", category: "Magic & Supernatural" },
  { value: "dwarves", label: "Dwarves", category: "Magic & Supernatural" },
  { value: "orcs", label: "Orcs / Goblins", category: "Magic & Supernatural" },
  { value: "giants", label: "Giants", category: "Magic & Supernatural" },
  { value: "merfolk", label: "Merfolk", category: "Magic & Supernatural" },
  { value: "elementals", label: "Elementals", category: "Magic & Supernatural" },
  { value: "spirits", label: "Spirits", category: "Magic & Supernatural" },
  { value: "talking-animals", label: "Talking Animals", category: "Magic & Supernatural" },
  { value: "familiar", label: "Familiar", category: "Magic & Supernatural" },

  // ── Love & Desire ──
  { value: "love", label: "Love", category: "Love & Desire" },
  { value: "passion", label: "Passion", category: "Love & Desire" },
  { value: "desire", label: "Desire", category: "Love & Desire" },
  { value: "lust", label: "Lust", category: "Love & Desire" },
  { value: "intimacy", label: "Intimacy", category: "Love & Desire" },
  { value: "romance", label: "Romance", category: "Love & Desire" },
  { value: "courtship", label: "Courtship", category: "Love & Desire" },
  { value: "seduction", label: "Seduction", category: "Love & Desire" },
  { value: "heartbreak", label: "Heartbreak", category: "Love & Desire" },
  { value: "longing", label: "Longing", category: "Love & Desire" },
  { value: "yearning", label: "Yearning", category: "Love & Desire" },
  { value: "platonic-love", label: "Platonic Love", category: "Love & Desire" },
  { value: "familial-love", label: "Familial Love", category: "Love & Desire" },
  { value: "self-love", label: "Self-Love", category: "Love & Desire" },
  { value: "obsession", label: "Obsession", category: "Love & Desire" },
  { value: "infatuation", label: "Infatuation", category: "Love & Desire" },
  { value: "unconditional-love", label: "Unconditional Love", category: "Love & Desire" },
  { value: "toxic-love", label: "Toxic Love", category: "Love & Desire" },
  { value: "lost-love", label: "Lost Love", category: "Love & Desire" },
  { value: "first-love", label: "First Love", category: "Love & Desire" },
  { value: "last-love", label: "Last Love", category: "Love & Desire" },
  { value: "eternal-love", label: "Eternal Love", category: "Love & Desire" },
  { value: "love-at-first-sight", label: "Love at First Sight", category: "Love & Desire" },
  { value: "arranged-marriage", label: "Arranged Marriage", category: "Love & Desire" },
  { value: "marriage-of-convenience", label: "Marriage of Convenience", category: "Love & Desire" },
  { value: "fake-dating", label: "Fake Dating", category: "Love & Desire" },
  { value: "one-bed-trope", label: "One Bed Trope", category: "Love & Desire" },
  { value: "forced-proximity", label: "Forced Proximity", category: "Love & Desire" },
  { value: "hurt-comfort", label: "Hurt / Comfort", category: "Love & Desire" },
  { value: "protective", label: "Protective / Possessive", category: "Love & Desire" },
  { value: "touch-starved", label: "Touch Starved", category: "Love & Desire" },
  { value: "mutual-pining", label: "Mutual Pining", category: "Love & Desire" },
  { value: "miscommunication", label: "Miscommunication", category: "Love & Desire" },
  { value: "groveling", label: "Groveling", category: "Love & Desire" },
  { value: "happily-ever-after", label: "Happily Ever After", category: "Love & Desire" },
  { value: "bittersweet-ending", label: "Bittersweet Ending", category: "Love & Desire" },
  { value: "tragic-romance", label: "Tragic Romance", category: "Love & Desire" },

  // ── Quest & Journey ──
  { value: "quest", label: "Quest", category: "Quest & Journey" },
  { value: "journey", label: "Journey", category: "Quest & Journey" },
  { value: "adventure", label: "Adventure", category: "Quest & Journey" },
  { value: "road-trip", label: "Road Trip", category: "Quest & Journey" },
  { value: "voyage", label: "Voyage", category: "Quest & Journey" },
  { value: "expedition", label: "Expedition", category: "Quest & Journey" },
  { value: "pilgrimage", label: "Pilgrimage", category: "Quest & Journey" },
  { value: "odyssey", label: "Odyssey", category: "Quest & Journey" },
  { value: "escape", label: "Escape", category: "Quest & Journey" },
  { value: "chase", label: "Chase", category: "Quest & Journey" },
  { value: "hunt", label: "Hunt", category: "Quest & Journey" },
  { value: "treasure-hunt", label: "Treasure Hunt", category: "Quest & Journey" },
  { value: "race-against-time", label: "Race Against Time", category: "Quest & Journey" },
  { value: "homecoming", label: "Homecoming", category: "Quest & Journey" },
  { value: "exile", label: "Exile", category: "Quest & Journey" },
  { value: "wanderer", label: "Wanderer", category: "Quest & Journey" },
  { value: "nomad", label: "Nomad", category: "Quest & Journey" },
  { value: "refugee", label: "Refugee Journey", category: "Quest & Journey" },
  { value: "initiation", label: "Initiation", category: "Quest & Journey" },
  { value: "trials", label: "Trials / Tests", category: "Quest & Journey" },
  { value: "labyrinth", label: "Labyrinth", category: "Quest & Journey" },
  { value: "underworld-journey", label: "Underworld Journey", category: "Quest & Journey" },
  { value: "descent", label: "Descent", category: "Quest & Journey" },
  { value: "ascent", label: "Ascent", category: "Quest & Journey" },
  { value: "threshold", label: "Threshold / Crossing", category: "Quest & Journey" },
  { value: "return", label: "Return", category: "Quest & Journey" },
  { value: "transformation", label: "Transformation", category: "Quest & Journey" },
  { value: "self-discovery", label: "Self-Discovery", category: "Quest & Journey" },
  { value: "hero", label: "Hero's Journey", category: "Quest & Journey" },
  { value: "anti-hero", label: "Anti-Hero's Journey", category: "Quest & Journey" },
  { value: "reluctant-hero", label: "Reluctant Hero", category: "Quest & Journey" },
  { value: "accidental-hero", label: "Accidental Hero", category: "Quest & Journey" },
  { value: "tragic-hero", label: "Tragic Hero", category: "Quest & Journey" },
  { value: "everyman-hero", label: "Everyman Hero", category: "Quest & Journey" },
  { value: "fellowship", label: "Fellowship / Party", category: "Quest & Journey" },
  { value: "ragtag-team", label: "Ragtag Team", category: "Quest & Journey" },
  { value: "lone-wolf", label: "Lone Wolf", category: "Quest & Journey" },
  { value: "reluctant-allies", label: "Reluctant Allies", category: "Quest & Journey" },

  // ── Revenge & Justice ──
  { value: "revenge", label: "Revenge", category: "Revenge & Justice" },
  { value: "vengeance", label: "Vengeance", category: "Revenge & Justice" },
  { value: "retribution", label: "Retribution", category: "Revenge & Justice" },
  { value: "vigilante", label: "Vigilante Justice", category: "Revenge & Justice" },
  { value: "eye-for-an-eye", label: "Eye for an Eye", category: "Revenge & Justice" },
  { value: "cycle-of-violence", label: "Cycle of Violence", category: "Revenge & Justice" },
  { value: "forgiveness", label: "Forgiveness", category: "Revenge & Justice" },
  { value: "mercy", label: "Mercy", category: "Revenge & Justice" },
  { value: "justice", label: "Justice", category: "Revenge & Justice" },
  { value: "injustice", label: "Injustice", category: "Revenge & Justice" },
  { value: "wrongful-conviction", label: "Wrongful Conviction", category: "Revenge & Justice" },
  { value: "corrupt-system", label: "Corrupt System", category: "Revenge & Justice" },
  { value: "courtroom-drama", label: "Courtroom Drama", category: "Revenge & Justice" },
  { value: "crime-and-punishment", label: "Crime and Punishment", category: "Revenge & Justice" },
  { value: "guilt", label: "Guilt", category: "Revenge & Justice" },
  { value: "innocence", label: "Innocence", category: "Revenge & Justice" },
  { value: "scapegoat", label: "Scapegoat", category: "Revenge & Justice" },
  { value: "framed", label: "Framed", category: "Revenge & Justice" },
  { value: "confession", label: "Confession", category: "Revenge & Justice" },
  { value: "testimony", label: "Testimony", category: "Revenge & Justice" },
  { value: "witness", label: "Witness", category: "Revenge & Justice" },
  { value: "alibi", label: "Alibi", category: "Revenge & Justice" },
  { value: "evidence", label: "Evidence", category: "Revenge & Justice" },
  { value: "investigation", label: "Investigation", category: "Revenge & Justice" },
  { value: "interrogation", label: "Interrogation", category: "Revenge & Justice" },
  { value: "manhunt", label: "Manhunt", category: "Revenge & Justice" },
  { value: "fugitive", label: "Fugitive", category: "Revenge & Justice" },
  { value: "on-the-run", label: "On the Run", category: "Revenge & Justice" },
  { value: "cat-and-mouse", label: "Cat and Mouse", category: "Revenge & Justice" },
  { value: "double-cross", label: "Double Cross", category: "Revenge & Justice" },
  { value: "twist-ending", label: "Twist Ending", category: "Revenge & Justice" },
  { value: "red-herring", label: "Red Herring", category: "Revenge & Justice" },
  { value: "unreliable-narrator", label: "Unreliable Narrator", category: "Revenge & Justice" },
  { value: "whodunit", label: "Whodunit", category: "Revenge & Justice" },
  { value: "howcatchem", label: "Howcatchem", category: "Revenge & Justice" },
  { value: "perfect-crime", label: "Perfect Crime", category: "Revenge & Justice" },
  { value: "unsolved", label: "Unsolved / Cold Case", category: "Revenge & Justice" },
];

export const ALL_THEME_VALUES = THEME_OPTIONS.map((t) => t.value);

export function getGroupedThemes(): Map<string, ThemeOption[]> {
  const map = new Map<string, ThemeOption[]>();
  for (const t of THEME_OPTIONS) {
    const group = map.get(t.category) || [];
    group.push(t);
    map.set(t.category, group);
  }
  return map;
}
