"""Default export presets - system presets for common export scenarios."""

from typing import Any

DEFAULT_PRESETS: list[dict[str, Any]] = [
    {
        "system_key": "clean_manuscript",
        "name": "Clean Manuscript",
        "description": "Polished manuscript for submission or editing. No notes or comments.",
        "format": "docx",
        "compile_type": "full",
        "format_style": "manuscript",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": False,
            "exclude_notes_comments": True,
            "exclude_highlights": True,
            "exclude_revision_marks": True,
            "include_unfinished": False,
        },
        "naming_pattern": "{project_title}_{profile}_{date}",
        "project_type": None,
    },
    {
        "system_key": "editor_review_copy",
        "name": "Editor Review Copy",
        "description": "Manuscript with comments and revision marks for editor feedback.",
        "format": "docx",
        "compile_type": "review_copy",
        "format_style": "manuscript",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": True,
            "exclude_notes_comments": False,
            "exclude_highlights": False,
            "exclude_revision_marks": False,
            "include_unfinished": True,
        },
        "naming_pattern": "{project_title}_EditorReview_{date}",
        "project_type": None,
    },
    {
        "system_key": "beta_reader_copy",
        "name": "Beta Reader Copy",
        "description": "Clean manuscript for beta readers. Includes synopsis and feedback form.",
        "format": "zip",
        "compile_type": "full",
        "format_style": "manuscript",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": False,
            "exclude_notes_comments": True,
            "exclude_highlights": True,
            "exclude_revision_marks": True,
            "include_unfinished": False,
        },
        "naming_pattern": "{project_title}_BetaReader_{date}",
        "project_type": "fiction",
    },
    {
        "system_key": "submission_copy",
        "name": "Submission Copy",
        "description": "Clean, professional manuscript for agent/publisher submission.",
        "format": "docx",
        "compile_type": "submission_copy",
        "format_style": "manuscript",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": False,
            "exclude_notes_comments": True,
            "exclude_highlights": True,
            "exclude_revision_marks": True,
            "include_unfinished": False,
        },
        "naming_pattern": "{project_title}_Submission_{date}",
        "project_type": None,
    },
    {
        "system_key": "print_friendly_draft",
        "name": "Print-Friendly Draft",
        "description": "Formatted for printing and physical review.",
        "format": "pdf",
        "compile_type": "full",
        "format_style": "print",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": True,
            "exclude_notes_comments": True,
            "exclude_highlights": True,
            "exclude_revision_marks": True,
            "include_unfinished": True,
        },
        "naming_pattern": "{project_title}_PrintDraft_{date}",
        "project_type": None,
    },
    {
        "system_key": "working_draft",
        "name": "Working Draft",
        "description": "Full draft with notes and revision marks for internal use.",
        "format": "docx",
        "compile_type": "working_draft",
        "format_style": "manuscript",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": False,
            "exclude_notes_comments": False,
            "exclude_highlights": False,
            "exclude_revision_marks": False,
            "include_unfinished": True,
        },
        "naming_pattern": "{project_title}_WorkingDraft_{date}",
        "project_type": None,
    },
    {
        "system_key": "ghostwriter_delivery_pack",
        "name": "Ghostwriter Delivery Pack",
        "description": "Complete handoff package: manuscript, synopsis, summaries, bio, handoff notes.",
        "format": "zip",
        "compile_type": "full",
        "format_style": "manuscript",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": False,
            "exclude_notes_comments": True,
            "exclude_highlights": True,
            "exclude_revision_marks": True,
            "include_unfinished": False,
        },
        "naming_pattern": "{project_title}_GhostwriterDelivery_Draft{version}",
        "project_type": "ghostwritten",
    },
    {
        "system_key": "workbook_export",
        "name": "Workbook Export",
        "description": "Printable sections with prompts and exercise blocks. Spacing-aware.",
        "format": "pdf",
        "compile_type": "full",
        "format_style": "print",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_headings": True,
            "include_section_titles": True,
            "exclude_notes_comments": True,
            "include_unfinished": False,
        },
        "naming_pattern": "{project_title}_Workbook_{date}",
        "project_type": "workbook",
    },
    {
        "system_key": "memoir_review_draft",
        "name": "Memoir Review Draft",
        "description": "Chaptered review copy with reflection-friendly formatting.",
        "format": "docx",
        "compile_type": "full",
        "format_style": "manuscript",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": True,
            "exclude_notes_comments": True,
            "include_unfinished": True,
        },
        "naming_pattern": "{project_title}_MemoirReview_{date}",
        "project_type": "memoir",
    },
    {
        "system_key": "sample_chapters_export",
        "name": "Sample Chapters Export",
        "description": "First 3 chapters or selected chapters for proposal/sample.",
        "format": "docx",
        "compile_type": "partial",
        "format_style": "manuscript",
        "options": {
            "include_title_page": True,
            "include_toc": False,
            "exclude_notes_comments": True,
            "chapter_ids": None,
            "max_chapters": 3,
        },
        "naming_pattern": "{project_title}_SampleChapters_{date}",
        "project_type": None,
    },
    {
        "system_key": "amazon_kdp_paperback",
        "name": "Amazon KDP Paperback",
        "description": "Print-ready PDF for Amazon KDP paperback interior. Margins and trim for 6x9 or 5.5x8.5.",
        "format": "pdf",
        "compile_type": "full",
        "format_style": "print",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": True,
            "exclude_notes_comments": True,
            "exclude_highlights": True,
            "exclude_revision_marks": True,
            "include_unfinished": False,
        },
        "naming_pattern": "{project_title}_KDP_Paperback_{date}",
        "project_type": None,
    },
    {
        "system_key": "amazon_kdp_ebook",
        "name": "Amazon KDP Ebook",
        "description": "EPUB formatted for Kindle Direct Publishing. Reflowable, chapter-linked.",
        "format": "epub",
        "compile_type": "full",
        "format_style": "ebook",
        "options": {
            "include_title_page": True,
            "include_toc": True,
            "include_acknowledgements": False,
            "exclude_notes_comments": True,
            "exclude_highlights": True,
            "exclude_revision_marks": True,
            "include_unfinished": False,
        },
        "naming_pattern": "{project_title}_KDP_Ebook_{date}",
        "project_type": None,
    },
]


def get_system_preset(system_key: str) -> dict[str, Any] | None:
    """Return system preset by key."""
    for p in DEFAULT_PRESETS:
        if p["system_key"] == system_key:
            return p.copy()
    return None


def get_all_system_presets() -> list[dict[str, Any]]:
    """Return all system presets."""
    return [p.copy() for p in DEFAULT_PRESETS]
